version: '3'
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile

    ports:
        - 8084:80

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    links:
      - db

  db:
    image: mysql:5.7

    ports:
      - 3306:3306

    volumes:
      - /home/computer/Work/projects/personal_databases/.mysql/my-products-dashboard-rest:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: computer@1.6
